### ISSUE TITLE
Use ghpages to publish

### ISSUE THREAD

**Issue by mdedetrich** [apache/incubator-pekko-site#13]
This is a follow up from the discussion at https://lists.apache.org/thread/otrrz34tjkrplvw75tcjc8cy5c72ohoc but the tl;dr is that ASF supports using ghpages to publish docs to a projects main site (in our case https://pekko.apache.org/), Apache Airflow is an example of a project that already does this (see https://github.com/apache/airflow-site/blob/fef1e7c0b409404d64bf97e5f68a030b974cf394/.asf.yaml#L41)

This is very good news, because there happens to be an sbt-plugin called sbt-site that automates all of this (see https://www.scala-sbt.org/sbt-site/publishing.html#publishing-to-github-pages-using-sbt-ghpages), I have also personally used this in another project I maintain (see https://github.com/aiven/guardian-for-apache-kafka/blob/main/build.sbt#L407 and https://github.com/aiven/guardian-for-apache-kafka/blob/main/build.sbt#L334).

Doing this allows us to not only get rid of the redundant [content](https://github.com/apache/incubator-pekko-site/tree/main/content) generated assets folder but also opens up an easy to automatically publish the main pekko site after a PR is pushed into main.

@pjfanning @jrudolph Any objections to doing this?

**Comment by mdedetrich** [comment]
Hmm looks like I spoke to soon and forgot that ghpages doesn't support htaccess, see https://stackoverflow.com/questions/13446435/is-there-an-alternative-to-htaccess-for-github-pages

**Comment by jrudolph** [comment]
If we drop the preconception that putting a website into source control is a bad thing, we have two working ways of providing a website, either from nightlies with `.htaccess` or by putting things directly into `asf-site`. I already showed a script how to create a branch for the asf-site branch if we want to put the final release docs directly there. Alternatively, we can put it to nightlies and manually or automatically adjust the `.htaccess` redirection. Let's try to make one of these work before coming up with new options.

**Comment by mdedetrich** [comment]
To start off this is really a nice to have, its not something that needs to be done now and the main reason I suggested ghpages is because if it did work it would have been very trivial to implement. Also this isn't about changing how the architecture/structure of how are docs/main site is designed, the intention wasn't to change/modify `.htaccess` or change from push based to pull + grabbing docs based site deployment. This was only about removing the manual publish steps at https://github.com/apache/incubator-pekko-site/wiki/Manual-Publishing .

That being said, after dicussing this on the INFRA mailing list and a little bit more thinking, I believe the best way to solve this problem is to create an sbt-asfpages plugin analogous to [sbt-ghpages](https://github.com/sbt/sbt-ghpages) to integrate into [sbt-site](https://www.scala-sbt.org/sbt-site/). This shouldn't be that much work because the current setup (where generated assets are ultimately committed into a separate branch) is very similar to how sbt-ghpages works.

@jrudolph FYI, one the underlying reason why https://github.com/apache/incubator-pekko-site/pull/14 was created was to eventually allow for the "merge into main and then automatically publish" workflow which sbt-site provides.

**Comment by jrudolph** [comment]
We can of course create a plugin, but it's also not more than a script with a few lines of code as demonstrated earlier.
