### ISSUE TITLE
docs: create toc and download page for website

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-site#3]
* We need a generic landing page for our website that allows users to choose pekko, pekko-http, pekko-grpc, etc docs - a bit like https://akka.io/docs/
* We also need a download page - a bit like https://spark.apache.org/downloads.html
* should use our pekko paradox plugin so we have same look and feel as rest of web site

**Comment by mdedetrich** [comment]
> should use our pekko paradox plugin so we have same look and feel as rest of web site

At the risk of sounding contrarian, I don't think this is necessarily a good thing. The paradox theme we use (which is material) looks a lot nicer and is well suited to docs. However for the home page (i.e. pekko.apache.org) in my view we need something that looks like a landing page, i.e. similar to https://akka.io/ or https://scala-lang.org/.
