### ISSUE TITLE
Apache Pekko version is labeled as `0.1.0` 

### ISSUE THREAD

**Issue by He-Pin** [apache/incubator-pekko-site#33]
![image](https://github.com/apache/incubator-pekko-site/assets/501740/462b3819-d765-4791-992f-437c31773617)

I think this should be 1.0.1

**Comment by Roiocam** [comment]
I see that the current release seems to be done [manually](https://github.com/apache/incubator-pekko-site/pull/18). 

The issue was that the project's version is not specified during the build. I suggest at least having a shell script to avoid some errors likes this.

**Comment by pjfanning** [comment]
The pages generated from this git repo do not relate specifically to any Pekko release. The docs generated for the modules have the correct release version on them. - eg https://pekko.apache.org/docs/pekko/current/

For the top level pages generated for this repo, it would be nice to exclude the version from the pages. I don't know if paradox supports this.

**Comment by Roiocam** [comment]
> The pages generated from this git repo do not relate specifically to any Pekko release. The docs generated for the modules have the correct release version on them. - eg https://pekko.apache.org/docs/pekko/current/

Fair enough

> For the top level pages generated for this repo, it would be nice to exclude the version from the pages. I don't know if sbt-paradox supports this.

Since the `sbt-paradox` already maintain by pekko community, i think the answer is yes.

**Comment by pjfanning** [comment]
this is fixed
