### ISSUE TITLE
Adding GH Action for detecting `content` folder changes

### ISSUE THREAD

**Issue by samueleresca** [apache/incubator-pekko-site#56]
Currently we update the `content` folder manually. 
As a developer, I need to make the changes and re-trigger the content folder creation as described below:
```
rm -rf content
mkdir content
sbt clean paradox
cp -r target/paradox/site/main/. content/
```
It would be great to include e GH Action to ensure that there is no difference between the `content` folder pushed in the branch and the result of `sbt clean paradox`. This approach would ensure that if the dev forget to update the content folder the CI of the PR fails.

**Comment by pjfanning** [comment]
Makes sense. Do you want to add a workflow that runs for pull requests? Same commands that you have in description with a git diff call.

**Comment by mdedetrich** [comment]
Im fine with this for now, I have already started working on `sbt-asfsite` which will make this redundant as it will automate everything at which point we can remove this check.
