### ISSUE TITLE
write a .htaccess file that redirects page requests to nightlies.apache.org 

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-site#6]
eg https://pekko.apache.org/docs/pekko/current/ redirecting to
https://nightlies.apache.org/pekko/docs/pekko/main-snapshot/docs/

**Comment by jrudolph** [comment]
Now also added redirects to Javadoc and Scaladoc:

* https://pekko.staged.apache.org/api/pekko/snapshot/org/apache/pekko/persistence/DeleteSnapshotsFailure.html
* https://pekko.staged.apache.org/japi/pekko-http/snapshot/org/apache/pekko/http/scaladsl/model/headers/Access$minusControl$minusExpose$minusHeaders$.html

**Comment by jrudolph** [comment]
https://github.com/apache/incubator-pekko-site/blob/5df9854c3e32fda3e2ef02742330ff49a5bff921/content/.htaccess#L1-L4

**Comment by jrudolph** [comment]
It seems to work well enough but, in fact, using `RewriteRule ... [P]` will mean that the reverse proxying might not be optimally working. Not sure, if that is a problem in practice with the nightly and the website server sitting close enough to each other.

**Comment by pjfanning** [comment]
This is done and committed - https://github.com/apache/incubator-pekko-site/blob/main/src/main/paradox/.htaccess

**Comment by pjfanning** [comment]
@jrudolph I tried to just tidy up the branches but now the `.htaccess` redirects have stopped working. Would you be able to have a look? I can't see anything that has changed in the `.htaccess` file and maybe the background job that the ASF runs to publish the site after the commits is no longer supporting the .htaccess.

**Comment by pjfanning** [comment]
@jrudolph I worked around the issue and just republished the `.htaccess` file
