### ISSUE TITLE
pekko home page needs all the ASF links

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-site#65]
recently refactored home page and the refactor removed all these important links

https://pekko.apache.org/samples.html has them

https://pekko.apache.org does not

<img width="234" alt="Screenshot 2024-01-17 at 11 18 32" src="https://github.com/apache/incubator-pekko-site/assets/11783444/98ad7f5d-4130-474d-a09a-a004a0a0b2d6">

**Comment by pjfanning** [comment]
@samueleresca would you have time to add these links back to the home page?

**Comment by samueleresca** [comment]
ACK on this, I will try to take a look at this as soon as possible. In the meantime, I approve #67

**Comment by pjfanning** [comment]
> ACK on this, I will try to take a look at this as soon as possible. In the meantime, I approve #67

https://pekko.apache.org/ is updated now. There is no urgency on getting a better solution done but I'll leave this open.

**Comment by samueleresca** [comment]
> > ACK on this, I will try to take a look at this as soon as possible. In the meantime, I approve #67
> 
> https://pekko.apache.org/ is updated now. There is no urgency on getting a better solution done but I'll leave this open.

Thanks for the help 👍🏻

**Comment by samueleresca** [comment]
@pjfanning unless objections,  I would close this one as the styling automatically applied for #67 and #68 seems working correctly
