### ISSUE TITLE
broken image links with latest pekko-sbt-paradox snapshots

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-pekko-site#95]
See https://pekko.apache.org/docs/pekko-http/current/ and look at top left

<img width="696" alt="image" src="https://github.com/apache/incubator-pekko-site/assets/11783444/d45adcc1-e9a9-47c9-8697-e58fe43a14b2">

The Pekko Logo has broken

The link is to https://pekko.apache.org/docs/pekko-http/current/assets/images/pekko_logo.png

Should be https://pekko.apache.org/assets/images/pekko_logo.png

Also - the Pekko favicon seems to not be working - probably a similar issue.

**Comment by pjfanning** [comment]
@samueleresca @mdedetrich would either of you be in a position to look into this? I don't know if other images are affected or if it is just the logo icon.

**Comment by samueleresca** [comment]
See: https://github.com/apache/incubator-pekko-sbt-paradox/pull/126#issuecomment-1975376571

**Comment by samueleresca** [comment]
So, I think the root cause of this was that some of the partials weren't overwritten in [incubator-pekko-sbt-paradox](https://github.com/apache/incubator-pekko-sbt-paradox). Therefore, some of the links where leading to 404, Refer to the PR above for the fix.

**Comment by pjfanning** [comment]
fixed now
